### ISSUE TITLE
File upload when no resource defined can result in NPE

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/metalnx-web#29]
File upload, in UploadController, calling UploadService. See logs

```
2017-12-14 13:34:31 INFO  UploadServiceImpl:135 - getting file path
2017-12-14 13:34:31 INFO  UploadServiceImpl:137 - file path:null/home/test1/foo/niehs_dev_commons.sh
2017-12-14 13:34:31 INFO  UploadServiceImpl:139 - get resource based on dest:undefined
2017-12-14 13:34:31 INFO  ResourceServiceImpl:107 - Find specific resource by name
2017-12-14 13:34:31 INFO  ResourceServiceImpl:61 - Find all resources in the grid
```

NB many of these resources have an empty resource host.

```
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=72048, name=testGetParentNameBug175Child, zone=zone1, type=, path=EMPTY_RESC_PATH, freeSpace=0, children=[], parent=testGetParentNameBug175Parent, status=, host=EMPTY_RESC_HOST, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=90087, name=ufs3, zone=zone1, type=, path=/tmp/ufs3, freeSpace=0, children=[], parent=repl_resc, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=90090, name=ufs6, zone=zone1, type=, path=/tmp/ufs6, freeSpace=0, children=[], parent=repl_resc, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=72050, name=testAddChildToParentDuplicate, zone=zone1, type=, path=EMPTY_RESC_PATH, freeSpace=0, children=[], parent=zone1, status=, host=EMPTY_RESC_HOST, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=90071, name=ufs, zone=zone1, type=, path=/tmp/ufs, freeSpace=0, children=[], parent=zone1, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=90088, name=ufs4, zone=zone1, type=, path=/tmp/ufs4, freeSpace=0, children=[], parent=repl_resc, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=10027, name=test1-resc3, zone=zone1, type=, path=/var/lib/irods/iRODS/Vault3, freeSpace=0, children=[], parent=testAddChildToParentDuplicate, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=10014, name=demoResc, zone=zone1, type=, path=/var/lib/irods/Vault, freeSpace=0, children=[], parent=zone1, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=90083, name=repl_resc, zone=zone1, type=, path=EMPTY_RESC_PATH, freeSpace=0, children=[], parent=zone1, status=, host=EMPTY_RESC_HOST, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=10026, name=test1-resc2, zone=zone1, type=, path=/var/lib/irods/iRODS/Vault2, freeSpace=0, children=[], parent=zone1, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=72047, name=testGetParentNameBug175Parent, zone=zone1, type=, path=EMPTY_RESC_PATH, freeSpace=0, children=[], parent=zone1, status=, host=EMPTY_RESC_HOST, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=90084, name=ufs0, zone=zone1, type=, path=/tmp/ufs0, freeSpace=0, children=[], parent=repl_resc, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=90089, name=ufs5, zone=zone1, type=, path=/tmp/ufs5, freeSpace=0, children=[], parent=repl_resc, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=72051, name=testAddParentDeferredResource, zone=zone1, type=, path=EMPTY_RESC_PATH, freeSpace=0, children=[], parent=zone1, status=, host=EMPTY_RESC_HOST, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=72055, name=testAddMissingChildToParentxxxx, zone=zone1, type=, path=EMPTY_RESC_PATH, freeSpace=0, children=[], parent=zone1, status=, host=EMPTY_RESC_HOST, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=90085, name=ufs1, zone=zone1, type=, path=/tmp/ufs1, freeSpace=0, children=[], parent=repl_resc, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=10025, name=test1-resc, zone=zone1, type=, path=/var/lib/irods/iRODS/Vault1, freeSpace=0, children=[], parent=zone1, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=72052, name=testAddDuplicateResource, zone=zone1, type=, path=EMPTY_RESC_PATH, freeSpace=0, children=[], parent=zone1, status=, host=EMPTY_RESC_HOST, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=90086, name=ufs2, zone=zone1, type=, path=/tmp/ufs2, freeSpace=0, children=[], parent=repl_resc, status=, host=server4.local, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=72049, name=testAddChildToParent, zone=zone1, type=, path=EMPTY_RESC_PATH, freeSpace=0, children=[], parent=zone1, status=, host=EMPTY_RESC_HOST, totalRecords=0, contextString=]
2017-12-14 13:34:31 INFO  ResourceServiceImpl:129 - getDataGridResource()
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:162 - got dataGridResource:DataGridResource [id=90314, name=comp_resc, zone=zone1, type=, path=EMPTY_RESC_PATH, freeSpace=0, children=[], parent=zone1, status=, host=EMPTY_RESC_HOST, totalRecords=0, contextString=]
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:82 - got all resources
2017-12-14 13:34:31 DEBUG ResourceServiceImpl:85 - sorted...
2017-12-14 13:34:31 INFO  ResourceServiceImpl:124 - resource found:null
2017-12-14 13:34:31 ERROR UploadServiceImpl:158 - Exception in upload processing
java.lang.NullPointerException
	at com.emc.metalnx.services.irods.UploadServiceImpl.upload(UploadServiceImpl.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy69.upload(Unknown Source)
	at com.emc.metalnx.controller.UploadController.upload(UploadController.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:595)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2017-12-14 13:34:31 ERROR UploadController:143 - DataGridException uploading file
com.emc.metalnx.core.domain.exceptions.DataGridException: Could not upload due to system exception
	at com.emc.metalnx.services.irods.UploadServiceImpl.upload(UploadServiceImpl.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy69.upload(Unknown Source)
	at com.emc.metalnx.controller.UploadController.upload(UploadController.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:595)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2017-12-14 13:34:31 ERROR HttpErrorController:70 - 500 - Internal Server Error
2017-12-14 13:34:31 INFO  HttpErrorController:71 - httpRequest:org.springframework.web.
```

**Comment by michael-conway** [comment]
input params from log

```
2017-12-14 13:42:00 DEBUG HttpResponseHandlerInterceptor:80 - added user prefs to model as 'dataGridUser':DataGridUser [id=1, dataGridId=10016, username=test1, additionalInfo=zone1, enabled=true, locale=en, forceFileOverwriting=false, userType=rodsadmin, advancedView=false, bookmarks=[], favorites=[]]
2017-12-14 13:42:08 INFO  UploadController:102 - upload()
2017-12-14 13:42:08 INFO  UploadController:115 - multipartFile:org.springframework.web.multipart.commons.CommonsMultipartFile@6c0ed6c7
2017-12-14 13:42:08 INFO  UploadController:124 - parsed parameters...
2017-12-14 13:42:08 INFO  UploadServiceImpl:69 - upload()
2017-12-14 13:42:08 INFO  UploadServiceImpl:77 - file:org.springframework.web.multipart.commons.CommonsMultipartFile@6c0ed6c7
2017-12-14 13:42:08 INFO  UploadServiceImpl:78 - targetPath:/zone1/home/test1/boo
2017-12-14 13:42:08 INFO  UploadServiceImpl:79 - computeCheckSum:false
2017-12-14 13:42:08 INFO  UploadServiceImpl:80 - replicateFile:false
2017-12-14 13:42:08 INFO  UploadServiceImpl:81 - replicationResc:undefined
2017-12-14 13:42:08 INFO  UploadServiceImpl:82 - destResc:undefined
2017-12-14 13:42:08 INFO  UploadServiceImpl:83 - overwrite:true
2017-12-14 13:42:08 INFO  UploadServiceImpl:95 - Setting default resource to undefined
2017-12-14 13:42:08 INFO  UploadServiceImpl:115 - targetFile:irods://test1@docker.for.mac.localhost:1247/zone1/home/test1/boo/niehs_dev_commons.sh
2017-12-14 13:42:08 INFO  UploadServiceImpl:127 - transfer complete, compute checksum if required
2017-12-14 13:42:08 INFO  UploadServiceImpl:138 - getting resourceMap for upload
2017-12-14 13:42:08 WARN  ResourceAOImpl:616 - unable to format resourceFreeSpac

```

this falls into code here in UploadServiceImpl

```java

// Getting list of resources for upload
			HashMap<String, String> resourceMap = null;
			logger.info("getting resourceMap for upload");

			ResourceAO resourceAO = is.getResourceAO();
			resourceMap = DataGridUtils.buildMapForResourcesNamesAndMountPoints(resourceAO.findAll());
			String objPath = targetFile.getCanonicalPath();
			logger.info("getting file path");
			String filePath = resourceMap.get(destResc) + objPath.substring(objPath.indexOf("/", 1), objPath.length());
			logger.info("file path:{}", filePath);

			logger.info("get resource based on dest:{}", destResc);
			DataGridResource dgDestResc = resourceService.find(destResc);
			String host = dgDestResc.getHost();

			logger.info("executing rules...");
			rs.execBamCramMetadataRule(host, objPath, filePath);
			rs.execVCFMetadataRule(host, objPath, filePath);
			rs.execPopulateMetadataRule(host, objPath);
			rs.execImageRule(host, objPath, filePath);
			rs.execIlluminaMetadataRule(dgDestResc, targetPath, objPath);
			rs.execManifestFileRule(host, targetPath, objPath, filePath);
			logger.info("rules executed");

			isFileUploaded = true;

```
